### ISSUE TITLE
Lost Magic research not working properly / missing localization

### ISSUE THREAD

**Issue by xJon** [KELETU66666/ReForbiddenMagic#1]
From https://github.com/SpitefulFox/LostMagic/issues/6.
Any idea what's happening there?

**Comment by linkbeta5** [comment]
Just for context, these pages I'm posting now are the Apocrypha page in the 1.5.2 version of the 1.12.2 Perfectly Complex pack. 
![image2](https://user-images.githubusercontent.com/125415804/229034230-c4cd8b35-5b27-44cb-af61-d25b814105b5.png)
![image1](https://user-images.githubusercontent.com/125415804/229034232-affb8181-d12e-4a40-b9c4-249a128ec75f.png)
![image3](https://user-images.githubusercontent.com/125415804/229034234-3c3efccd-8530-4afe-90fb-a2156daa4404.png)

**Comment by linkbeta5** [comment]
But upon updating to the 1.5.3 version of the 1.12.2 perfectly complex pack is when this page replaced the "Lost Magic" research and won't complete even after I click "complete"
![229018449-e7112cb3-73d0-498d-8692-60fced000b06](https://user-images.githubusercontent.com/125415804/229034536-b4787863-95e9-472a-b9bf-88f178f823d7.png)

**Comment by linkbeta5** [comment]
If there's any more details please don't hesitate to ask.

**Comment by KELETU66666** [comment]
This doesn't affect the game at all, it's just that there is no text

**Comment by xJon** [comment]
@KELETU66666 If the Apocrypha pages are broken & the player presses on "complete" and nothing happens it's a pretty buggy experience.

**Comment by KELETU66666** [comment]
fixed
