### ISSUE TITLE
Crashes with Dependencies

### ISSUE THREAD

**Issue by andrewan719** [KELETU66666/ReForbiddenMagic#2]
The mod will register a crash during loading if Blood Magic is installed as an optional dependency without Botania. The mod works as normal when neither mod is downloaded, or if both mods are downloaded.

Crash Log:
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Uh... Did I do that?

Time: 2023-11-14 11:20:20 PST
Description: Initializing game

java.lang.NoClassDefFoundError: vazkii/botania/common/item/block/ItemBlockSpecialFlower
    at keletu.forbiddenmagicre.compat.bloodmagic.BMRecipes.registerRecipes(BMRecipes.java:14)
    at WayofTime.bloodmagic.util.PluginUtil$RegistrationStep.lambda$static$1(PluginUtil.java:123)
    at WayofTime.bloodmagic.util.PluginUtil.handlePluginStep(PluginUtil.java:88)
    at WayofTime.bloodmagic.core.RegistrarBloodMagicRecipes.registerRecipes(RegistrarBloodMagicRecipes.java:59)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_182_RegistrarBloodMagicRecipes_registerRecipes_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:7101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.ClassNotFoundException: vazkii.botania.common.item.block.ItemBlockSpecialFlower
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 24 more
Caused by: java.lang.NullPointerException

(MixinBooter) Mixins in Stacktrace:
    net/minecraft/client/Minecraft:
        mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperClient (mixins.tweaks.misc.buttons.snooper.client.json) [unknown-location]
        zone.rong.loliasm.common.crashes.mixins.MinecraftMixin (mixins.crashes.json) [unknown-location]
        dev.redstudio.alfheim.mixin.client.MinecraftMixin (mixins.alfheim.json) [unknown-location]
        io.github.lxgaming.sledgehammer.mixin.core.client.MinecraftAccessor (mixins.sledgehammer.core.json) [unknown-location]
        zone.rong.loliasm.client.searchtree.mixins.vanilla.MinecraftMixin (mixins.searchtree_vanilla.json) [unknown-location]
        io.github.lxgaming.sledgehammer.mixin.core.client.MinecraftMixin (mixins.sledgehammer.core.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.performance.fps.mixin.UTUncapFPSMixin (mixins.tweaks.performance.fps.json) [unknown-location]
        de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json) [unknown-location]
        meldexun.renderlib.mixin.MixinMinecraft (mixins.renderlib.json) [unknown-location]
        zone.rong.loliasm.client.mcfixes.mixins.mc186052.MinecraftMixin (mixins.fix_mc186052.json) [unknown-location]
        dev.redstudio.valkyrie.mixin.MinecraftMixin (mixins.valkyrie.json) [unknown-location]
    net/minecraftforge/fml/client/FMLClientHandler:
        org.embeddedt.vintagefix.mixin.dynamic_resources.MixinFMLClientHandler (mixins.vintagefix.json) [unknown-location]
    net/minecraftforge/registries/GameData:
        org.dimdev.jeid.mixin.core.MixinGameData (mixins.jeid.core.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.performance.prefixcheck.mixin.UTPrefixCheckMixin (mixins.tweaks.performance.prefixcheck.json) [unknown-location]
    net/minecraft/client/Minecraft:
        mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperClient (mixins.tweaks.misc.buttons.snooper.client.json) [unknown-location]
        zone.rong.loliasm.common.crashes.mixins.MinecraftMixin (mixins.crashes.json) [unknown-location]
        dev.redstudio.alfheim.mixin.client.MinecraftMixin (mixins.alfheim.json) [unknown-location]
        io.github.lxgaming.sledgehammer.mixin.core.client.MinecraftAccessor (mixins.sledgehammer.core.json) [unknown-location]
        zone.rong.loliasm.client.searchtree.mixins.vanilla.MinecraftMixin (mixins.searchtree_vanilla.json) [unknown-location]
        io.github.lxgaming.sledgehammer.mixin.core.client.MinecraftMixin (mixins.sledgehammer.core.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.performance.fps.mixin.UTUncapFPSMixin (mixins.tweaks.performance.fps.json) [unknown-location]
        de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json) [unknown-location]
        meldexun.renderlib.mixin.MixinMinecraft (mixins.renderlib.json) [unknown-location]
        zone.rong.loliasm.client.mcfixes.mixins.mc186052.MinecraftMixin (mixins.fix_mc186052.json) [unknown-location]
        dev.redstudio.valkyrie.mixin.MinecraftMixin (mixins.valkyrie.json) [unknown-location]
    net/minecraftforge/fml/client/FMLClientHandler:
        org.embeddedt.vintagefix.mixin.dynamic_resources.MixinFMLClientHandler (mixins.vintagefix.json) [unknown-location]
    net/minecraftforge/registries/GameData:
        org.dimdev.jeid.mixin.core.MixinGameData (mixins.jeid.core.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.performance.prefixcheck.mixin.UTPrefixCheckMixin (mixins.tweaks.performance.prefixcheck.json) [unknown-location]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 11 (amd64) version 10.0
  Java Version: 1.8.0_391, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1721396048 bytes (1641 MB) / 3562536960 bytes (3397 MB) up to 6524764160 bytes (6222 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms500m -Xmx7000m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: Powered by §cValkyrie 0.2-Dev-10§r 124 mods loaded, 124 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                       | Version                             | Source                                                      | Signature                                |
       |:----- |:------------------------ |:----------------------------------- |:----------------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                | 1.12.2                              | minecraft.jar                                               | None                                     |
       | LCH   | mcp                      | 9.42                                | minecraft.jar                                               | None                                     |
       | LCH   | FML                      | 8.0.99.99                           | forge-1.12.2-14.23.5.2860-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                    | 14.23.5.2860                        | forge-1.12.2-14.23.5.2860-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | mixinbooter              | 8.9                                 | minecraft.jar                                               | None                                     |
       | LCH   | configanytime            | 1.0                                 | !configanytime-1.0.jar                                      | None                                     |
       | LCH   | redcore                  | 0.5-Dev-5                           | !Red-Core-MC-1.7-1.12-0.5-Dev-5.jar                         | None                                     |
       | LCH   | forgelin                 | 1.8.4                               | Forgelin-1.8.4.jar                                          | None                                     |
       | LCH   | baubles                  | 1.5.2                               | Baubles-1.12-1.5.2.jar                                      | None                                     |
       | LCH   | thaumcraft               | 6.1.BETA26                          | Thaumcraft-1.12.2-6.1.BETA26.jar                            | None                                     |
       | LCH   | thaumic_arcana           | 1.2.0                               | Thaumic+Arcana-1.3.1.jar                                    | None                                     |
       | LCH   | jei                      | 4.25.1                              | HadEnoughItems_1.12.2-4.25.1.jar                            | None                                     |
       | LCH   | abyssalcraft             | 1.10.4                              | AbyssalCraft-1.12.2-1.10.4.jar                              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | mantle                   | 1.12-1.3.3.55                       | Mantle-1.12-1.3.3.55.jar                                    | None                                     |
       | LCH   | tconstruct               | 1.12.2-2.13.0.183                   | TConstruct-1.12.2-2.13.0.183.jar                            | None                                     |
       | LCH   | acintegration            | 1.11.3                              | AbyssalCraft+Integration-1.12.2-1.11.3.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
       | LCH   | embers                   | 1.19                                | EmbersRekindled-1.19.jar                                    | None                                     |
       | LCH   | aetheriumashenarmor      | 1.0.2                               | Aetherium+Ashen+Armor-Release-1.12.2-1.2.1.jar              | None                                     |
       | LCH   | aetherworks              | 1.12.2-1.0.0.3                      | AetherWorks-1.12.2-1.0.0.3.jar                              | None                                     |
       | LCH   | afraidofthedark          | 1.3.0                               | afraidofthedark-1.12.2-1.3.0.jar                            | None                                     |
       | LCH   | akashictome              | 1.2-12                              | AkashicTome-1.2-12.jar                                      | None                                     |
       | LCH   | alfheim                  | 1.1-Dev-2                           | Alfheim-1.1-Dev-2.jar                                       | None                                     |
       | LCH   | guideapi                 | 1.12-2.1.8-63                       | Guide-API-1.12-2.1.8-63.jar                                 | None                                     |
       | LCH   | bloodmagic               | 1.12.2-2.4.3-105                    | BloodMagic-1.12.2-2.4.3-105.jar                             | None                                     |
       | LCH   | theoneprobe              | 1.4.28                              | theoneprobe-1.12-1.4.28.jar                                 | None                                     |
       | LCH   | animus                   | 1                                   | Animus-1.12-2.1.8.jar                                       | None                                     |
       | LCH   | antiqueatlas             | 4.6.3                               | antiqueatlas-1.12.2-4.6.3(2).jar                            | None                                     |
       | LCH   | antiqueatlasoverlay      | 1.2                                 | antiqueatlas-1.12.2-4.6.3(2).jar                            | None                                     |
       | LCH   | appleskin                | 1.0.14                              | AppleSkin-mc1.12-1.0.14.jar                                 | None                                     |
       | LCH   | appliedenergistics2      | rv6-stable-7-extended_life-v0.55.14 | appliedenergistics2-rv6-stable-7-extended_life-v0.55.14.jar | None                                     |
       | LCH   | lemonlib                 | 1.3.0                               | lemonlib-1.12.2-1.3.0.jar                                   | None                                     |
       | LCH   | arcaneworld              | 0.0.11                              | arcane-world-fixed-1.0.jar.jar                              | None                                     |
       | LCH   | gbook_snapshot           | 2.9.1.s5                            | Guidebook-1.12.2-2.9.1.s5.jar                               | None                                     |
       | LCH   | arcanearchives           | 0.2.0.25-mixins8                    | arcanearchives-0.2.0.25-mixins8.jar                         | None                                     |
       | LCH   | atlaslib                 | 1.1.5a                              | Atlas-Lib-1.12.2-1.1.5a.jar                                 | None                                     |
       | LCH   | morphtool                | 1.2-21                              | Morph-o-Tool-1.2-21.jar                                     | None                                     |
       | LCH   | autoreglib               | 1.3-32                              | AutoRegLib-1.3-32.jar                                       | None                                     |
       | LCH   | elementaristics          | 0.0.9.6.7                           | elementaristics-0.0.9.6.7.jar                               | None                                     |
       | LCH   | patchouli                | 1.0-23.6                            | Patchouli-1.0-23.6(2).jar                                   | None                                     |
       | LCH   | bewitchment              | 0.22.63                             | bewitchment-1.12.2-0.0.22.64.jar                            | None                                     |
       | LCH   | beyondtheveil            | 1.12.2-0.3.2                        | BeyondTheVeil-1.12.2-0.3.2.jar                              | None                                     |
       | LCH   | bloodsmeltery            | 1.1.2                               | Blood-Smeltery-1.12.2-1.1.2.jar                             | None                                     |
       | LCH   | bloodarsenal             | 1.12.2-2.2.2-31                     | BloodArsenal-1.12.2-2.2.2-31.jar                            | None                                     |
       | LCH   | conarm                   | 1.2.5.10                            | conarm-1.12.2-1.2.5.10.jar                                  | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
       | LCH   | bloodtinker              | 1.0.5                               | bloodtinker-1.0.5.jar                                       | None                                     |
       | LCH   | loliasm                  | 5.18                                | censoredasm5.18.jar                                         | None                                     |
       | LCH   | comforts                 | 1.4.1.3                             | comforts-1.12.2-1.4.1.3.jar                                 | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | controlling              | 3.0.10                              | Controlling-3.0.12.2.jar                                    | None                                     |
       | LCH   | corvus                   | 1.2.3                               | corvus-1.12.2-1.2.3.jar                                     | None                                     |
       | LCH   | craftingtweaks           | 9.0.1                               | CraftingTweaks_1.12.2-9.0.1(1).jar                          | None                                     |
       | LCH   | crimsonrevelations       | 0.8                                 | crimsonrevelations-0.8.jar                                  | None                                     |
       | LCH   | crimsonwarfare           | 1.5                                 | crimsonwarfare-1.5.jar                                      | None                                     |
       | LCH   | cyclopscore              | 1.6.7                               | CyclopsCore-1.12.2-1.6.7.jar                                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | defiledlands             | 1.4.3                               | defiledlands-1.12.2-1.4.3.jar                               | None                                     |
       | LCH   | ding                     | 1.0.2                               | Ding-1.12.2-1.0.2.jar                                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | dynview                  | 1.3                                 | dynviewdist-1.12-1.3(1).jar                                 | None                                     |
       | LCH   | embersified              | 1.0.3                               | Embersified-1.12.2-1.0.3.jar                                | None                                     |
       | LCH   | enchantingwiththaumcraft | 1.3                                 | enchantingwiththaumcraft-1.4.jar                            | None                                     |
       | LCH   | evilcraft                | 0.10.78                             | EvilCraft-1.12.2-0.10.78.jar                                | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | evilcraftcompat          | 1.0.0                               | EvilCraft-1.12.2-0.10.78.jar                                | None                                     |
       | LCH   | xporbclump               | 2.0                                 | Fixeroo-2.0.jar                                             | None                                     |
       | LCH   | lostmagic                | 1.0                                 | lostmagic-1.0.3.jar                                         | None                                     |
       | LCH   | forbiddenmagicre         | 0.5.1                               | forbiddenmagic-0.5.1.jar                                    | None                                     |
       | LCH   | hammercore               | 12.2.38                             | HammerLib-1.12.2-12.2.38.jar                                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | thaumadditions           | 12.7.8                              | ThaumicAdditions-1.12.2-12.7.8.jar                          | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCH   | llibrary                 | 1.7.20                              | llibrary-1.7.20-1.12.2.jar                                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire               | 1.9.1-1.3.0                         | IceAndFireRotN-1.9.1-1.3.0.jar                              | None                                     |
       | LCH   | ichoriumkit              | 0.2.3.2                             | ichoriumkit-0.2.3.3.jar                                     | None                                     |
       | LCH   | inventorytweaks          | 1.63+release.109.220f184            | InventoryTweaks-1.63.jar                                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | isorropia                | 0.1.13                              | isorropia-1.12.2-0.1.14.jar                                 | None                                     |
       | LCH   | jeresources              | 0.9.2.60                            | JustEnoughResources-1.12.2-0.9.2.60.jar                     | None                                     |
       | LCH   | libnine                  | 1.2.1                               | libnine-1.12.2-1.2.1.jar                                    | None                                     |
       | LCH   | librarianlib             | 4.22                                | librarianlib-1.12.2-4.22.jar                                | None                                     |
       | LCH   | mahoutsukai              | 1.12.2-v1.19.55                     | mahoutsukai-1.12.2-v1.19.55.jar                             | None                                     |
       | LCH   | mousetweaks              | 3.1.4                               | mousetweaks-1.12.2-3.1.4.jar                                | None                                     |
       | LCH   | naturescompass           | 1.8.5                               | NaturesCompass-1.12.2-1.8.5.jar                             | None                                     |
       | LCH   | netherportalfix          | 5.3.17                              | NetherPortalFix_1.12.1-5.3.17(1).jar                        | None                                     |
       | LCH   | renderlib                | 1.3.2                               | RenderLib-1.12.2-1.3.2(1).jar                               | None                                     |
       | LCH   | nothirium                | 0.3.4-beta                          | Nothirium-1.12.2-0.3.4-beta.jar                             | None                                     |
       | LCH   | overpoweredarmorbar      | @VERSION@                           | overloadedarmorbar-1.0.4g.jar                               | None                                     |
       | LCH   | particleculling          | v1.4.1                              | particleculling-1.12.2-v1.4.1.jar                           | None                                     |
       | LCH   | placebo                  | 1.6.0                               | Placebo-1.12.2-1.6.1.jar                                    | None                                     |
       | LCH   | soot                     | 1.10-hotfix                         | Soot-1.10-hotfix.jar                                        | None                                     |
       | LCH   | thaumicaugmentation      | 1.12.2-2.1.11                       | ThaumicAugmentation-1.12.2-2.1.11.jar                       | None                                     |
       | LCH   | thaumicwonders           | 1.8.2                               | thaumicwonders-1.8.2.jar                                    | None                                     |
       | LCH   | planarartifice           | 1.4.0-pre7                          | planarartifice-1.4.0-pre7.jar                               | None                                     |
       | LCH   | plustic                  | 8.0.6                               | plustic-8.0.6.jar                                           | None                                     |
       | LCH   | pyromancy                | 1.6.0.2                             | Pyromancy+1.6.0.2+for+MC+1.12.2.jar                         | None                                     |
       | LCH   | jeid                     | 2.0.6                               | RoughlyEnoughIDs-2.0.6.jar                                  | None                                     |
       | LCH   | roughtweaks              | 1.0                                 | roughTweaks0.2.4-1.12.2.jar                                 | None                                     |
       | LCH   | rustic                   | 1.1.7                               | rustic-1.1.7.jar                                            | None                                     |
       | LCH   | rusticthaumaturgy        | 4.4a                                | Rustic+Thaumaturgy-4.4a.jar                                 | None                                     |
       | LCH   | rusticwitchcraft         | 1.0.2                               | rusticwitcraft-1.0.2.jar                                    | None                                     |
       | LCH   | satako                   | 2.26                                | Satako+1.12-2.26.jar                                        | None                                     |
       | LCH   | shadowlegacy             | 1.0.0                               | Shadow+Legacy+1.1.2+Beta.jar                                | None                                     |
       | LCH   | sledgehammer             | 1.12.2-2.0.25                       | Sledgehammer-1.12.2-2.0.25.jar                              | None                                     |
       | LCH   | spartanshields           | 1.5.5                               | SpartanShields-1.12.2-1.5.5.jar                             | None                                     |
       | LCH   | tc6aspects4jei           | 0.0.2a                              | tc6aspects4jei-0.0.2a.jar                                   | None                                     |
       | LCH   | tconevo                  | 1.0.44                              | tconevo-1.12.2-1.0.44.jar                                   | None                                     |
       | LCH   | thaumic_calculator       | 0.4                                 | Thaumic+Calculations-1.12.2-0.4.jar                         | None                                     |
       | LCH   | thaumiconeprobe          | 1.0.0                               | thaumic-one-probe-1.12.2-1.0.0.jar                          | None                                     |
       | LCH   | tg                       | 0.1.6.0                             | Thaumic_Gadgets_1.12.2_0.1.6_tb.26.jar                      | None                                     |
       | LCH   | thaumicbases             | 3.5.200.1                           | thaumicbases-3.5.200.1.jar                                  | None                                     |
       | LCH   | thaumicbrewing           | 1.0.2                               | thaumicbrewing-1.0.2.jar                                    | None                                     |
       | LCH   | thaumicjei               | 1.6.0                               | ThaumicJEI-1.12.2-1.6.0-27.jar                              | None                                     |
       | LCH   | thaumicenergistics       | 2.2.6                               | thaumicenergistics-extended_life-2.2.7.jar                  | None                                     |
       | LCH   | tcinventoryscan          | 2.0.10                              | ThaumicInventoryScanning_1.12.2-2.0.10.jar                  | None                                     |
       | LCH   | thaumicperiphery         | 0.3.1                               | thaumicperiphery-0.3.1.jar                                  | None                                     |
       | LCH   | thaumictinkerer          | 1.12.2-5.0-620a0c5                  | thaumictinkerer-1.12.2-5.0-620a0c5.jar                      | None                                     |
       | LCH   | thaumtweaks              | 0.3.5.3                             | thaumtweaks-0.3.5.3.jar                                     | None                                     |
       | LCH   | tinkertoolleveling       | 1.12.2-1.1.0.DEV.b23e769            | TinkerToolLeveling-1.12.2-1.1.0.jar                         | None                                     |
       | LCH   | tipthescales             | 1.0.4                               | TipTheScales-1.12.2-1.0.4.jar                               | None                                     |
       | LCH   | tombstone                | 4.6.2                               | tombstone-4.6.2-1.12.2.jar                                  | None                                     |
       | LCH   | universaltweaks          | 1.12.2-1.8.0                        | UniversalTweaks-1.12.2-1.8.0.jar                            | None                                     |
       | LCH   | valkyrie                 | 0.2-Dev-10                          | Valkyrie-0.2-Dev-10.jar                                     | None                                     |
       | LCH   | vampirism                | 1.6.2                               | Vampirism-1.12.2-1.6.2.jar                                  | None                                     |
       | LCH   | teamlapen-lib            | 1.6.2                               | Vampirism-1.12.2-1.6.2.jar                                  | None                                     |
       | LCH   | vampirism_integrations   | vampirism_integrations              | VampirismIntegrations-1.12.2-1.3.0.jar                      | None                                     |
       | LCH   | vintagefix               | 0.3.3                               | vintagefix-0.3.3.jar                                        | None                                     |
       | LCH   | voicechat                | 1.12.2-2.4.24                       | voicechat-forge-1.12.2-2.4.24.jar                           | None                                     |
       | LCH   | warptheory               | 0.0.3.5                             | WarpTheory1.12.2-0.0.3.5.jar                                | None                                     |
       | LCH   | wizardry                 | 0.11.1                              | wizardry-0.11.1.jar                                         | None                                     |
       | LCH   | librarianliblate         | 4.22                                | librarianlib-1.12.2-4.22.jar                                | None                                     |
       | LCH   | mysticallib              | 1.12.2-1.13.0                       | mysticallib-1.12.2-1.13.0.jar                               | None                                     |
  Loaded coremods (and transformers): ValkyriePlugin (Valkyrie-0.2-Dev-10.jar)
                                        
                                      AALoadingPlugin (arcanearchives-0.2.0.25-mixins8.jar)
                                        
                                      LibrarianLib Plugin (librarianlib-1.12.2-4.22.jar)
                                        com.teamwizardry.librarianlib.asm.LibLibTransformer
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.4.1.jar)
                                        
                                      iceandfire (IceAndFireRotN-1.9.1-1.3.0.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
                                        
                                      VintageFix (vintagefix-0.3.3.jar)
                                        org.embeddedt.vintagefix.transformer.ASMModParserTransformer
                                      Wizardry Plugin (wizardry-0.11.1.jar)
                                        com.teamwizardry.wizardry.asm.WizardryTransformer
                                      UniversalTweaksCore (UniversalTweaks-1.12.2-1.8.0.jar)
                                        
                                      Red Core (!Red-Core-MC-1.7-1.12-0.5-Dev-5.jar)
                                        
                                      AlfheimPlugin (Alfheim-1.1-Dev-2.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      TconEvoCoreMod (tconevo-1.12.2-1.0.44.jar)
                                        xyz.phanta.tconevo.coremod.TconEvoClassTransformer
                                      LoliASM (censoredasm5.18.jar)
                                        
                                      RenderLibPlugin (RenderLib-1.12.2-1.3.2(1).jar)
                                        meldexun.renderlib.asm.RenderLibClassTransformer
                                      Planar Artifice Coremod (planarartifice-1.4.0-pre7.jar)
                                        leppa.planarartifice.core.PATransformer
                                      Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.11.jar)
                                        thecodex6824.thaumicaugmentation.core.TATransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      Fixeroo (Fixeroo-2.0.jar)
                                        
                                      NothiriumPlugin (Nothirium-1.12.2-0.3.4-beta.jar)
                                        meldexun.nothirium.mc.asm.NothiriumClassTransformer
                                      MixinBooter (!mixinbooter-8.9.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      HCASM (HammerLib-1.12.2-12.2.38.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      JustEnoughIDs Extension Plugin (RoughlyEnoughIDs-2.0.6.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      ConfigAnytimePlugin (!configanytime-1.0.jar)
                                        
                                      TARCore (ThaumicAdditions-1.12.2-12.7.8.jar)
                                        
                                      AE2ELCore (appliedenergistics2-rv6-stable-7-extended_life-v0.55.14.jar)
                                        appeng.core.transformer.AE2ELTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 527.37' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - craftingtweaksIntegration (Enabled/Not Forced)
                                   - theoneprobeIntegration (Enabled/Not Forced)
  AE2 Version: stable rv6-stable-7-extended_life-v0.55.14 for Forge 14.23.5.2847
  HammerCore Debug Information: Dependent Mods:
                                -Thaumic Additions: Reconstructed (thaumadditions) @ 12.7.8
  Patchouli open book context: n/a
  Suspected Mods: ReForbiddenMagic (forbiddenmagicre), Blood Magic: Alchemical Wizardry (bloodmagic), Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.37, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 5800HS with Radeon Graphics

**Comment by KELETU66666** [comment]
sorry for reply so late...
i'll try my best to fix it :)

**Comment by KELETU66666** [comment]
fixed :)
