### ISSUE TITLE
Rapier of the Strix impossible to craft

### ISSUE THREAD

**Issue by thegenghistkhan** [KELETU66666/ReForbiddenMagic#4]
The infusion recipe for the rapier of the strix requires a vitium crystal that has 100 vitium essence instead of the normal 1.

![2024-05-14_16 09 24](https://github.com/KELETU66666/ReForbiddenMagic/assets/144782216/161cd8db-005e-402a-b00a-0b52b78f2345)

**Comment by KELETU66666** [comment]
fixed :)
